<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:discourse="http://www.discourse.org/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>PySpice - Latest topics</title>
    <link>https://pyspice.discourse.group/latest</link>
    <description>Latest topics</description>
    
      <lastBuildDate>Mon, 31 Jan 2022 19:46:50 +0000</lastBuildDate>
      <atom:link href="https://pyspice.discourse.group/latest.rss" rel="self" type="application/rss+xml" />
        <item>
          <title>Error while using 3 terminal Resistors</title>
          <dc:creator><![CDATA[natarajpinakapani]]></dc:creator>
          <category>Dev</category>
          <description><![CDATA[
            <p>I get an error when using 3 terminal resistors from Skywater 130nm PDK. When I looked at BasicElements.py, I noticed that all resistors are defined as DipoleElements. I have added a class for 3 terminal devices and now I am able to simulate the circuit.  The same is true for 3-terminal capacitors too.</p>
<p>I would like to contribute PySpice to make it compatible with Skywater 130nm PDK devices. Kindly let me know what would be best way to contribute</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/error-while-using-3-terminal-resistors/164">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/error-while-using-3-terminal-resistors/164</link>
          <pubDate>Mon, 31 Jan 2022 19:46:50 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-164</guid>
          <source url="https://pyspice.discourse.group/t/error-while-using-3-terminal-resistors/164.rss">Error while using 3 terminal Resistors</source>
        </item>
        <item>
          <title>Simulating a circuit with 16 MOSFETs: True gmin stepping error</title>
          <dc:creator><![CDATA[dsalman]]></dc:creator>
          <category>Circuit Simulation</category>
          <description><![CDATA[
            <p>Hello,</p>
<p>I am trying to simulate a circuit using 16 MOSFETS.</p>
<p>The issue is that once the MOSFETS’s 15 and 16 are placed in the schematic, it results in an error: PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR</p>
<p>If the MOSFET’s 15 and 16 are commented out, then the code compiles.</p>
<p>I am using NGspice-34.dll and PySpice 1.5. Have also tested with Pyspice 1.4.3 and NGspice-32.dll.</p>
<p>Is NGSpice reaching some maximum nodes/complexity limit? OR is this an issue with mosfet model? OR it is a circuit netlist (floating node?) issue?</p>
<p>Any help or ideas would be greatly appreciated.</p>
<p>The code and error message are reproduced below.</p>
<p>Thanks</p>
<p>Kahless96</p>
<p>##***********************************************<br>
import math<br>
import numpy as np<br>
import matplotlib.pyplot as plt<br>
from matplotlib.widgets import Cursor<br>
from matplotlib.pyplot import semilogx<br>
from matplotlib import pyplot</p>
<p>import PySpice.Logging.Logging as Logging<br>
logger = Logging.setup_logging()</p>
<p>from PySpice.Doc.ExampleTools import find_libraries<br>
from PySpice.Probe.Plot import plot<br>
from PySpice.Spice.Library import SpiceLibrary<br>
from PySpice.Spice.Netlist import Circuit<br>
from PySpice.Unit import *</p>
<p>from engineering_notation import EngNumber</p>
<p>##***********************************************</p>
<h2>
<a name="circuit-netlist-1" class="anchor" href="https://pyspice.discourse.group#circuit-netlist-1"></a>Circuit Netlist</h2>
<p>circuit = Circuit(‘MyCircuit’)</p>
<p>libraries_path = find_libraries()<br>
spice_library = SpiceLibrary(libraries_path)<br>
circuit.include(spice_library[‘ptm65nm_nmos’])<br>
circuit.include(spice_library[‘ptm65nm_pmos’])</p>
<h1>
<a name="define-inputs-2" class="anchor" href="https://pyspice.discourse.group#define-inputs-2"></a>Define inputs</h1>
<p>HIGH = 1@u_V<br>
LOW = 0@u_V<br>
f_D = 1@u_Hz<br>
f_C = f_D/2<br>
f_B = f_D/4<br>
f_A = f_D/8</p>
<p>steptime=1@u_ms<br>
finaltime = 8/f_D<br>
circuit.V(1, ‘Vdd’, circuit.gnd,       HIGH@u_V)<br>
circuit.PulseVoltageSource(2, ‘A’, circuit.gnd,<br>
initial_value=HIGH, pulsed_value=LOW,<br>
pulse_width=(1/f_A)/2, period=1/f_A)<br>
circuit.PulseVoltageSource(3, ‘B’, circuit.gnd,<br>
initial_value=HIGH, pulsed_value=LOW,<br>
pulse_width=(1/f_B)/2, period=1/f_B)<br>
circuit.PulseVoltageSource(4, ‘C’, circuit.gnd,<br>
initial_value=HIGH, pulsed_value=LOW,<br>
pulse_width=(1/f_C)/2, period=1/f_C)<br>
circuit.PulseVoltageSource(5, ‘D’, circuit.gnd,<br>
initial_value=HIGH, pulsed_value=LOW,<br>
pulse_width=(1/f_D)/2, period=1/f_D)</p>
<h1>
<a name="m-name-drain-node-gate-node-source-node-bulksubstrate-node-3" class="anchor" href="https://pyspice.discourse.group#m-name-drain-node-gate-node-source-node-bulksubstrate-node-3"></a>M    <source> &lt;bulk/substrate node&gt;
</h1>
<p>circuit.MOSFET(1, ‘out1’, ‘A’, ‘Vdd’, ‘Vdd’, model=‘ptm65nm_pmos’)<br>
circuit.MOSFET(2, ‘out1’, ‘B’, ‘Vdd’, ‘Vdd’, model=‘ptm65nm_pmos’)<br>
circuit.MOSFET(3, ‘out1’, ‘A’, ‘temp’, circuit.gnd, model=‘ptm65nm_nmos’)<br>
circuit.MOSFET(4, ‘temp’,‘B’, circuit.gnd, circuit.gnd, model=‘ptm65nm_nmos’)<br>
circuit.MOSFET(5, ‘out2’, ‘out1’, circuit.gnd, circuit.gnd, model=‘ptm65nm_nmos’)<br>
circuit.MOSFET(6, ‘out2’, ‘out1’, ‘Vdd’, ‘Vdd’, model=‘ptm65nm_pmos’)<br>
circuit.MOSFET(7, ‘out3’, ‘C’, ‘Vdd’, ‘Vdd’, model=‘ptm65nm_pmos’)<br>
circuit.MOSFET(8, ‘out3’, ‘D’, ‘Vdd’, ‘Vdd’, model=‘ptm65nm_pmos’)<br>
circuit.MOSFET(9, ‘out3’, ‘C’, ‘temp1’, circuit.gnd, model=‘ptm65nm_nmos’)<br>
circuit.MOSFET(10, ‘temp1’,‘D’, circuit.gnd, circuit.gnd, model=‘ptm65nm_nmos’)<br>
circuit.MOSFET(11, ‘out4’, ‘out3’, circuit.gnd, circuit.gnd, model=‘ptm65nm_nmos’)<br>
circuit.MOSFET(12, ‘out4’, ‘out3’, ‘Vdd’, ‘Vdd’, model=‘ptm65nm_pmos’)<br>
circuit.MOSFET(13, ‘op’, ‘out2’, ‘Vdd’, ‘Vdd’, model=‘ptm65nm_pmos’)<br>
circuit.MOSFET(14, ‘op’, ‘out4’, ‘Vdd’, ‘Vdd’, model=‘ptm65nm_pmos’)<br>
circuit.MOSFET(15, ‘op’, ‘out2’, ‘temp2’, circuit.gnd, model=‘ptm65nm_nmos’)<br>
circuit.MOSFET(16, ‘temp2’,‘out4’, circuit.gnd, circuit.gnd, model=‘ptm65nm_nmos’)</p>
<p>##***********************************************</p>
<h2>
<a name="simulation-transient-analysis-4" class="anchor" href="https://pyspice.discourse.group#simulation-transient-analysis-4"></a>Simulation: Transient Analysis</h2>
<p>simulator = circuit.simulator(temperature=25, nominal_temperature=25)<br>
analysis = simulator.transient(step_time=steptime, end_time=finaltime)</p>
<p>#########################</p>
<h1>
<a name="plotting-commands-5" class="anchor" href="https://pyspice.discourse.group#plotting-commands-5"></a>PLOTTING COMMANDS</h1>
<p>figure = plt.subplots(figsize=(11, 6))<br>
axe = plt.subplot(111)<br>
plt.xlabel(‘Time [s]’)<br>
plt.ylabel(‘Voltage [V]’)<br>
plt.grid()<br>
plot(analysis[‘op’], axis=axe, color=‘red’)<br>
plt.show()</p>
<p>Here is the error messages after which it fails to run:</p>
<p>2022-01-13 14:24:25,298 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Note: Starting true gmin stepping<br>
2022-01-13 14:24:25,298 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-03 Note: One successful gmin step<br>
2022-01-13 14:24:25,298 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-04 Note: One successful gmin step<br>
2022-01-13 14:24:25,298 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-05 Note: One successful gmin step<br>
2022-01-13 14:24:25,298 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-06 Note: One successful gmin step<br>
2022-01-13 14:24:25,298 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-07 Note: One successful gmin step<br>
2022-01-13 14:24:25,298 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-08 Note: One successful gmin step<br>
2022-01-13 14:24:25,298 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-09 Note: One successful gmin step<br>
2022-01-13 14:24:25,314 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-10 Note: One successful gmin step<br>
2022-01-13 14:24:25,314 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-11 Note: One successful gmin step<br>
2022-01-13 14:24:25,314 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-12 Note: One successful gmin step<br>
2022-01-13 14:24:25,314 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Trying gmin =   1.0000E-12 Note: One successful gmin step<br>
2022-01-13 14:24:25,314 - PySpice.Spice.NgSpice.Shared.NgSpiceShared - Shared.ERROR - Note: True gmin stepping completed</p>
<p>I have seen this gmin stepping error in other forum posts but in those cases it was related to circuit netlist error. This does not seem to be the case here.</p>
<p>The mosfet models being used are provided with Pyspice.</p>
            <p><small>2 posts - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/simulating-a-circuit-with-16-mosfets-true-gmin-stepping-error/162">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/simulating-a-circuit-with-16-mosfets-true-gmin-stepping-error/162</link>
          <pubDate>Thu, 13 Jan 2022 03:55:35 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-162</guid>
          <source url="https://pyspice.discourse.group/t/simulating-a-circuit-with-16-mosfets-true-gmin-stepping-error/162.rss">Simulating a circuit with 16 MOSFETs: True gmin stepping error</source>
        </item>
        <item>
          <title>Problems with running simulator</title>
          <dc:creator><![CDATA[AMK]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>Hi every one!<br>
I am new to PySpice. I was running 1.4.3 ver with ngspice 3.2 and everything was working well.<br>
My computer did a usual clean up and update.</p>
<p>Now the netlist part works fine. But when I call the simulator I get a long error message (I will paste below). I was doing good progress and I am glad to share a 3 phase diode rectifier model which was working well. Until this problem arose. When I did an update I see that the cur ver is 1.5 and installs ngspice 3.4</p>
<p>Any help is appreciated. Else will have to go back to LTspice</p>
<p>Error msg attached below</p>
<hr>
<p>TypeError                                 Traceback (most recent call last)<br>
 in <br>
----&gt; 1 simulator = circuit3.simulator(temperature=25, nominal_temperature=25)<br>
2 simulator.initial_condition(out = 90@u_V)<br>
3 analysis = simulator.transient(step_time=Vac.period/1000, end_time=Vac.period*6)<br>
4<br>
5 res = format_output(analysis)</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\Netlist.py in simulator(self, *args, **kwargs)</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\Simulation.py in factory(cls, circuit, *args, **kwargs)<br>
1117     “”" This class implements a circuit simulator. Each analysis mode is performed by a method that<br>
1118     return the measured probes.<br>
 → 1119<br>
1120     For <em>ac</em> and <em>transient</em> analyses, the user must specify a list of nodes using the <em>probes</em> key<br>
1121     argument.</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\NgSpice\Simulation.py in <strong>init</strong>(self, circuit, **kwargs)<br>
97         ngspice_shared = kwargs.get(‘ngspice_shared’, None)<br>
98         if ngspice_shared is None:<br>
—&gt; 99             self._ngspice_shared = NgSpiceShared.new_instance()<br>
100         else:<br>
101             self._ngspice_shared = ngspice_shared</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\NgSpice\Shared.py in new_instance(cls, ngspice_id, send_data, verbose)<br>
450             cls._instances[ngspice_id] = instance<br>
451             return instance<br>
 → 452<br>
453     ##############################################<br>
454</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\NgSpice\Shared.py in <strong>init</strong>(self, ngspice_id, send_data, verbose)<br>
478         self._library_path = None<br>
479         self._load_library(verbose)<br>
 → 480         self._init_ngspice(send_data)<br>
481<br>
482         self._is_running = False</p>
<p>~\Anaconda3\lib\site-packages\PySpice\Spice\NgSpice\Shared.py in _load_library(self, verbose)<br>
511             if ‘SPICE_LIB_DIR’ not in os.environ:<br>
512                 _ = str(Path(self.NGSPICE_PATH).joinpath(‘share’, ‘ngspice’))<br>
 → 513                 os.environ[‘SPICE_LIB_DIR’] = _<br>
514                 # self._logger.warning(‘Set SPICE_LIB_DIR = %s’, _)<br>
515</p>
<p>~\Anaconda3\lib\pathlib.py in <strong>new</strong>(cls, *args, **kwargs)<br>
1036         if cls is Path:<br>
1037             cls = WindowsPath if os.name == ‘nt’ else PosixPath<br>
 → 1038         self = cls._from_parts(args, init=False)<br>
1039         if not self._flavour.is_supported:<br>
1040             raise NotImplementedError(“cannot instantiate %r on your system”</p>
<p>~\Anaconda3\lib\pathlib.py in _from_parts(cls, args, init)<br>
677         # right flavour.<br>
678         self = object.<strong>new</strong>(cls)<br>
 → 679         drv, root, parts = self._parse_args(args)<br>
680         self._drv = drv<br>
681         self._root = root</p>
<p>~\Anaconda3\lib\pathlib.py in _parse_args(cls, args)<br>
661                 parts += a._parts<br>
662             else:<br>
 → 663                 a = os.fspath(a)<br>
664                 if isinstance(a, str):<br>
665                     # Force-cast str subclasses to str (issue <span class="hashtag">#21127</span>)</p>
<p>TypeError: expected str, bytes or os.PathLike object, not NoneType</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/problems-with-running-simulator/153">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/problems-with-running-simulator/153</link>
          <pubDate>Thu, 11 Nov 2021 13:45:39 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-153</guid>
          <source url="https://pyspice.discourse.group/t/problems-with-running-simulator/153.rss">Problems with running simulator</source>
        </item>
        <item>
          <title>Howto: Transient analysis</title>
          <dc:creator><![CDATA[overthere]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>I want to do a transient analysis of a square wave.</p>
<ol>
<li>How do I do a transient analysis and plot the output?</li>
<li>How do I implement a square wave?</li>
</ol>
<p>I found nothing in the examples. Thanks for your help,<br>
Michael</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/howto-transient-analysis/150">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/howto-transient-analysis/150</link>
          <pubDate>Mon, 27 Sep 2021 20:08:15 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-150</guid>
          <source url="https://pyspice.discourse.group/t/howto-transient-analysis/150.rss">Howto: Transient analysis</source>
        </item>
        <item>
          <title>How to write .func in pyspice and use it in behavioral source?</title>
          <dc:creator><![CDATA[sant]]></dc:creator>
          <category>Circuit Simulation</category>
          <description><![CDATA[
            <p>I want to write a .func that will help me designing a device model. I used **raw_spice=’ …’ **  but it is not working. I am new in pyspice.</p>
<p>Thank yuo</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/how-to-write-func-in-pyspice-and-use-it-in-behavioral-source/148">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/how-to-write-func-in-pyspice-and-use-it-in-behavioral-source/148</link>
          <pubDate>Thu, 16 Sep 2021 00:26:03 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-148</guid>
          <source url="https://pyspice.discourse.group/t/how-to-write-func-in-pyspice-and-use-it-in-behavioral-source/148.rss">How to write .func in pyspice and use it in behavioral source?</source>
        </item>
        <item>
          <title>How to get voltage acrros two points to write behavioral voltage source expression?</title>
          <dc:creator><![CDATA[sant]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>I am new with pyspice. I want to add a behavioral voltage source to my circuit. To write its expression we need voltage across two points x and y. For example v=2*Voltage(x,y)</p>
<p>Will anyone share the syntax in pyspice?<br>
Thank you.</p>
            <p><small>6 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/how-to-get-voltage-acrros-two-points-to-write-behavioral-voltage-source-expression/147">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/how-to-get-voltage-acrros-two-points-to-write-behavioral-voltage-source-expression/147</link>
          <pubDate>Fri, 10 Sep 2021 13:08:01 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-147</guid>
          <source url="https://pyspice.discourse.group/t/how-to-get-voltage-acrros-two-points-to-write-behavioral-voltage-source-expression/147.rss">How to get voltage acrros two points to write behavioral voltage source expression?</source>
        </item>
        <item>
          <title>Interrupted simulation multiple sources</title>
          <dc:creator><![CDATA[tombalabomba]]></dc:creator>
          <category>Circuit Simulation</category>
          <description><![CDATA[
            <p>Hi everyone,</p>
<p>for a research project I’m working on control strategies for PFC circuits and therefore I need to simulate a passive circuit in conjunction with two half bridges.<br>
Problem is that I need the simulation to interact with a python script since I need to calculate the control signals of the two half bridges externally and thus the simualtion flow is as follows.</p>
<p>First, I need to initialize the simulation which basically means that I need to sample the amplitude and phase of a sinusodial source representing the grid voltage and the component values and initial conditions of the passive components. Next, I need to run the simulation in chunks where I first calculate the four control signals of the half bridges based on the current and voltage signals of the passive circuit followed by a chunk of transient simulation for a given time span (sample rate of the controller).</p>
<p>I tried to implement this flow but I unfortunately I struggle with the following issues.</p>
<p>a) Phase of the AC source:<br>
I tired SinusoidalVoltageSource() but I failed to specify a phase offset. Altough it’s base class SinusoidalMixin() offers a delay attribute, it seems that it just enables the source after a given time and thus this isn’t the desired behaviour for my purpose. Alternatively, I defined my own grid voltage using a NgSpiceShared object according …/examples/ngspice-shared/external-source.html.<br>
This essential does the trick for me but leaves with the next problem.</p>
<p>b) Multiple External Sources:<br>
Give the simulation flow above I need to run the simulation with at least four external sources, two for every half bridge, and five if I define the grid voltage also as external source. So I wonder how I define multiple shared objects.</p>
<p>c) Setting the initial conditions<br>
Since I run the simulation in chunks I wonder if I have to preload the nodes with the latest values and I need to run the simulation with start_time=0 and end_time=timespan according the controller’s sample rate or are the states kept internally and I need just to run the simulation with start_time=(k-1)<em>timespan, end_time=k</em>timespan in order to run the kth simulation chunk.</p>
<p>Any help is kindly appreciated!</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/interrupted-simulation-multiple-sources/144">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/interrupted-simulation-multiple-sources/144</link>
          <pubDate>Wed, 11 Aug 2021 15:05:52 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-144</guid>
          <source url="https://pyspice.discourse.group/t/interrupted-simulation-multiple-sources/144.rss">Interrupted simulation multiple sources</source>
        </item>
        <item>
          <title>Library import corner analysis</title>
          <dc:creator><![CDATA[junsang]]></dc:creator>
          <category>NgSpice</category>
          <description><![CDATA[
            <p>Hello!</p>
<p>I am not familiar with English so if there is something not clear, please ask me!!</p>
<p>I am trying to import library file using corner analysis<br>
The code below is what I wish to use in NgSpice text</p>
<pre><code class="lang-auto">.lib 'mm018.l' TT
</code></pre>
<p>Since there is “TT” added for typical type analysis,<br>
I can’t use the library import using the code below in pyspice</p>
<pre><code class="lang-auto">spice_library = SpiceLibrary('./library_to_add')
</code></pre>
<p>I have no idea how I should solve this problem, please help me</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/library-import-corner-analysis/143">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/library-import-corner-analysis/143</link>
          <pubDate>Mon, 09 Aug 2021 06:01:08 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-143</guid>
          <source url="https://pyspice.discourse.group/t/library-import-corner-analysis/143.rss">Library import corner analysis</source>
        </item>
        <item>
          <title>Divide one AC-analysis waveform by another</title>
          <dc:creator><![CDATA[thicksheik]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>I have run an AC analysis in PySpice.<br>
I have found the waveform for input (source) voltage, and input (source) current.<br>
Now I would like to find the impedance waveform (voltage/current)<br>
How can I divide one waveform by another?</p>
<p>Thanks for your help!</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/divide-one-ac-analysis-waveform-by-another/140">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/divide-one-ac-analysis-waveform-by-another/140</link>
          <pubDate>Fri, 28 May 2021 12:53:00 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-140</guid>
          <source url="https://pyspice.discourse.group/t/divide-one-ac-analysis-waveform-by-another/140.rss">Divide one AC-analysis waveform by another</source>
        </item>
        <item>
          <title>Extract array of complex numbers from waveform</title>
          <dc:creator><![CDATA[thicksheik]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>Hi</p>
<p>I am just getting started with PySpice.</p>
<p>I have run an AC analysis on a netlist using PySpice, and have extracted my waveforms, but would like to convert these into a numpy array of complex numbers - how do I do this?</p>
<p>I want to do further mathematical analysis on the PySpice Waveform output.</p>
<p>Thanks</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/extract-array-of-complex-numbers-from-waveform/139">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/extract-array-of-complex-numbers-from-waveform/139</link>
          <pubDate>Fri, 28 May 2021 12:50:00 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-139</guid>
          <source url="https://pyspice.discourse.group/t/extract-array-of-complex-numbers-from-waveform/139.rss">Extract array of complex numbers from waveform</source>
        </item>
        <item>
          <title>Extract float-type number from class &#39;PySpice.Unit.Unit.UnitValue&#39;</title>
          <dc:creator><![CDATA[thicksheik]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>Hi</p>
<p>I am just getting started with using PySpice.</p>
<p>I have extracted voltage/current values from a PySpice analysis, and would like to analyze these using other Python functions.</p>
<p>But all of my values are now of type class ‘PySpice.Unit.Unit.UnitValue’.</p>
<p>How can I remove the units, so that these are just normal float numbers?</p>
<p>Thanks</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/extract-float-type-number-from-class-pyspice-unit-unit-unitvalue/138">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/extract-float-type-number-from-class-pyspice-unit-unit-unitvalue/138</link>
          <pubDate>Fri, 28 May 2021 12:44:13 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-138</guid>
          <source url="https://pyspice.discourse.group/t/extract-float-type-number-from-class-pyspice-unit-unit-unitvalue/138.rss">Extract float-type number from class &#39;PySpice.Unit.Unit.UnitValue&#39;</source>
        </item>
        <item>
          <title>Whats PySpice&#39;s Advantages?</title>
          <dc:creator><![CDATA[bcalbatros]]></dc:creator>
          <category>Help</category>
          <description><![CDATA[
            <p>Hi friends, why I have use pySpice instead of use direct spice program? Whats advantages of using pyspice? I must a homework like electronic circuits with pyspice but I didn’t find a topic.  Can you help me find a topic. How can I do with pyspice?</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/whats-pyspices-advantages/135">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/whats-pyspices-advantages/135</link>
          <pubDate>Tue, 18 May 2021 20:26:00 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-135</guid>
          <source url="https://pyspice.discourse.group/t/whats-pyspices-advantages/135.rss">Whats PySpice&#39;s Advantages?</source>
        </item>
        <item>
          <title>Can SpiceParser parse subcircuits?</title>
          <dc:creator><![CDATA[jimzenn]]></dc:creator>
          <category>Help</category>
          <description><![CDATA[
            <p>We want to parse a sp file with a netlist that embeds a subcircuit definition. When we parse it with SpiceParser we noticed that the subcircuit definition is removed. Is there a way to include the subcircuit definition during the parsing process?</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/can-spiceparser-parse-subcircuits/133">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/can-spiceparser-parse-subcircuits/133</link>
          <pubDate>Fri, 30 Apr 2021 03:23:54 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-133</guid>
          <source url="https://pyspice.discourse.group/t/can-spiceparser-parse-subcircuits/133.rss">Can SpiceParser parse subcircuits?</source>
        </item>
        <item>
          <title>NgSpice Options Help</title>
          <dc:creator><![CDATA[az743]]></dc:creator>
          <category>NgSpice</category>
          <description><![CDATA[
            <p>How do you use the simulation options in a simulation?  For example how does one call up any of the options in chapter 15.1 of the NgSpice users guide.</p>
<p>Say I want to change the transient solver to METHOD=‘Gear’ how would I?</p>
            <p><small>2 posts - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/ngspice-options-help/131">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/ngspice-options-help/131</link>
          <pubDate>Sun, 21 Mar 2021 01:18:42 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-131</guid>
          <source url="https://pyspice.discourse.group/t/ngspice-options-help/131.rss">NgSpice Options Help</source>
        </item>
        <item>
          <title>Error in running examples</title>
          <dc:creator><![CDATA[GillB]]></dc:creator>
          <category>Help</category>
          <description><![CDATA[
            <p>I’ve just installed PySpice (on Fedora, using pip install PySpice). I’ve downloaded the examples with pyspice-post-installation --download-example and tried to run them. I get a number of errors, but the one that appears most often is:</p>
<p>pyspice-post-installation --download-example</p>
<p>I googled the problem but couldn’t fix it, grateful for suggestions.</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/error-in-running-examples/127">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/error-in-running-examples/127</link>
          <pubDate>Tue, 09 Mar 2021 23:43:16 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-127</guid>
          <source url="https://pyspice.discourse.group/t/error-in-running-examples/127.rss">Error in running examples</source>
        </item>
        <item>
          <title>Google COLAB + PySpice</title>
          <dc:creator><![CDATA[LeandroVB]]></dc:creator>
          <category>Help</category>
          <description><![CDATA[
            <p>I trying use PySpice on google Colab, but I fail…<br>
Some one  can tell me if is possible, and how i can do?</p>
<p>Aparently… I should but i dont be able to install or reference there the “ngspice dll”</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/google-colab-pyspice/125">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/google-colab-pyspice/125</link>
          <pubDate>Sun, 07 Mar 2021 02:56:43 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-125</guid>
          <source url="https://pyspice.discourse.group/t/google-colab-pyspice/125.rss">Google COLAB + PySpice</source>
        </item>
        <item>
          <title>Read a NgSpice rawfile using PySpice</title>
          <dc:creator><![CDATA[Wallflower]]></dc:creator>
          <category>Help</category>
          <description><![CDATA[
            <p>Hello guys,</p>
<p>I am writing a python script that generates, runs and eventually will read the raw files. The command I use to run the netlist is the following: <code>subprocess.run([path_to_ngspice_executable,'-r','rawfile.raw','-b','-i',my_netlist])</code> which generates my rawfile.</p>
<p>Could you please tell me what PySpice command to use so I can read the generated raw file and plot the distribution of my voltages?</p>
<p>Thanks in advance !</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/read-a-ngspice-rawfile-using-pyspice/123">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/read-a-ngspice-rawfile-using-pyspice/123</link>
          <pubDate>Wed, 03 Mar 2021 08:40:44 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-123</guid>
          <source url="https://pyspice.discourse.group/t/read-a-ngspice-rawfile-using-pyspice/123.rss">Read a NgSpice rawfile using PySpice</source>
        </item>
        <item>
          <title>More maintainers?</title>
          <dc:creator><![CDATA[endolith]]></dc:creator>
          <category>Dev</category>
          <description><![CDATA[
            <p>There are currently 113 open issues and 18 pull requests, including some <a href="https://github.com/FabriceSalvaire/PySpice/pull/261/files" rel="noopener nofollow ugc">very trivial ones</a> from months ago, many unfinished pages in the documentation, and no changes to the repo for 7 months.</p>
<p>I know you work on this in your free time and development will be sporadic, would you be willing to add additional maintainers to help deal with the PRs, etc?</p>
            <p><small>4 posts - 3 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/more-maintainers/120">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/more-maintainers/120</link>
          <pubDate>Tue, 09 Feb 2021 23:42:59 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-120</guid>
          <source url="https://pyspice.discourse.group/t/more-maintainers/120.rss">More maintainers?</source>
        </item>
        <item>
          <title>Getting keyerror while running example</title>
          <dc:creator><![CDATA[Sky77]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>As i’m new to pyspice when i am running this example<br>
<a href="https://pyspice.fabrice-salvaire.fr/releases/v1.3/examples/diode/diode-characteristic-curve.html" rel="noopener nofollow ugc">https://pyspice.fabrice-salvaire.fr/releases/v1.3/examples/diode/diode-characteristic-curve.html</a></p>
<p>I am getting this keyerror </p><div class="lightbox-wrapper"><a class="lightbox" href="https://aws1.discourse-cdn.com/free1/uploads/pyspice/original/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372.jpeg" data-download-href="/uploads/short-url/wEDXbmSH7xJG7wRDx5Jm9EdbCWm.jpeg?dl=1" title="IMG_20210130_184031" rel="noopener nofollow ugc"><img src="https://aws1.discourse-cdn.com/free1/uploads/pyspice/optimized/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372_2_477x500.jpeg" alt="IMG_20210130_184031" data-base62-sha1="wEDXbmSH7xJG7wRDx5Jm9EdbCWm" width="477" height="500" srcset="https://aws1.discourse-cdn.com/free1/uploads/pyspice/optimized/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372_2_477x500.jpeg, https://aws1.discourse-cdn.com/free1/uploads/pyspice/optimized/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372_2_715x750.jpeg 1.5x, https://aws1.discourse-cdn.com/free1/uploads/pyspice/original/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372.jpeg 2x" data-small-upload="https://aws1.discourse-cdn.com/free1/uploads/pyspice/optimized/1X/e4ddbf4c44c60a3f0af2c891aaffd47a4b842372_2_10x10.png"></a></div><p></p>
<p>I m using windows 10 64 bit<br>
Ide : Anaconda python<br>
Pyspice 1.4.3<br>
Ngspice 32</p>
<p>If any gentlemen has idea how to fix this it ll help me a lot <img src="https://emoji.discourse-cdn.com/twitter/smiley.png?v=9" title=":smiley:" class="emoji" alt=":smiley:"></p>
            <p><small>4 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/getting-keyerror-while-running-example/119">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/getting-keyerror-while-running-example/119</link>
          <pubDate>Sat, 30 Jan 2021 13:14:32 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-119</guid>
          <source url="https://pyspice.discourse.group/t/getting-keyerror-while-running-example/119.rss">Getting keyerror while running example</source>
        </item>
        <item>
          <title>Installation example scripts</title>
          <dc:creator><![CDATA[cyber-g]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>Dear PySpice community, I would like to share some installation example files to illustrate the installation procedure of PySpice on Linux by using <code>apt</code> and <code>pip</code> only.</p>
<p>Those files are published as Dockerfile scripts since they allow full automatic machine instantiation with <code>docker</code>.<br>
They cover both Ubuntu and Debian, using a standard approach using only <code>apt</code> :</p>
<ul>
<li><a href="https://github.com/cyber-g/debian-pyspice-std" class="inline-onebox" rel="noopener nofollow ugc">GitHub - cyber-g/debian-pyspice-std: A Dockerfile to demonstrate the installation of PySpice on Debian</a></li>
<li><a href="https://github.com/cyber-g/ubuntu-pyspice-std" class="inline-onebox" rel="noopener nofollow ugc">GitHub - cyber-g/ubuntu-pyspice-std: A Dockerfile to demonstrate the installation of PySpice on Ubuntu</a></li>
</ul>
<p>One can also find a more “manual” approach to demonstrate how to properly set the <code>PYTHONPATH</code> and <code>LD_LIBRARY_PATH</code> environment variables :</p>
<ul>
<li><a href="https://github.com/cyber-g/debian-pyspice-semi-custom" class="inline-onebox" rel="noopener nofollow ugc">GitHub - cyber-g/debian-pyspice-semi-custom: A Dockerfile to demonstrate the installation of PySpice on Debian using a "manual" installation of libngspice</a></li>
<li><a href="https://github.com/cyber-g/ubuntu-pyspice-semi-custom" class="inline-onebox" rel="noopener nofollow ugc">GitHub - cyber-g/ubuntu-pyspice-semi-custom: A Dockerfile to demonstrate the installation of PySpice on Ubuntu using a "manual" installation of libngspice</a></li>
</ul>
<p>The two latter should be useful for those who want to install PySpice on Google Collab.</p>
<p>If you have docker on your computer, you can also pull directly the images from Docker Hub :</p>
<ul>
<li><a href="https://hub.docker.com/repository/docker/drdpham/pyspice-debian" rel="noopener nofollow ugc">Docker Hub PySpice Debian</a></li>
<li><a href="https://hub.docker.com/repository/docker/drdpham/pyspice-ubuntu" rel="noopener nofollow ugc">Docker Hub PySpice Ubuntu</a></li>
</ul>
<p>Enjoy !</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/installation-example-scripts/117">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/installation-example-scripts/117</link>
          <pubDate>Mon, 25 Jan 2021 22:35:44 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-117</guid>
          <source url="https://pyspice.discourse.group/t/installation-example-scripts/117.rss">Installation example scripts</source>
        </item>
        <item>
          <title>Access to Diode Parameters</title>
          <dc:creator><![CDATA[Martin_Sauter]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>Hello,</p>
<p>when working with pyspice 1.3 it was possible for me to change device parameters in thie way described below. With 1.4 this does not seem to work any more. Is there a new or alternate syntax?</p>
<p>#############################<br>
import os<br>
os.linesep="\n"</p>
<p>source=’’’<br>
.title xxx</p>
<p>V1 N001 0 1 AC 1<br>
D1 N001 0 john</p>
<p>.model john D (Is=4.352e-9 Rs=0 N=1.906)<br>
.end</p>
<p>‘’’</p>
<p>parser = SpiceParser(source=source)<br>
circuit = parser.build_circuit()</p>
<p>circuit.john._parameters[‘Is’] = 3e-08</p>
<p>simulator = circuit.simulator(temperature=25, nominal_temperature=25)<br>
analysis = simulator.dc(V1=slice(0.1, 1,0.01))</p>
<p>#######################################</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/access-to-diode-parameters/108">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/access-to-diode-parameters/108</link>
          <pubDate>Sat, 19 Dec 2020 17:38:44 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-108</guid>
          <source url="https://pyspice.discourse.group/t/access-to-diode-parameters/108.rss">Access to Diode Parameters</source>
        </item>
        <item>
          <title>Two installation experiences on Windows</title>
          <dc:creator><![CDATA[endolith]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <h2>Windows 10</h2>
<p>First I tried to install in my base conda environment on Windows 10 64-bit.  It could not be installed due to package conflicts and it tried many different things to resolve the conflicts, grinding away at the CPU for two hours, and eventually I killed it.</p>
<p>Then I created a new environment specifically for PySpice and installed it:</p>
<pre><code class="lang-auto">conda create --name pyspice
conda activate pyspice
conda install -c conda-forge pyspice
pyspice-post-installation --install-ngspice-dll
</code></pre>
<p>This last step did not work, however, because it required the<br>
<code>requests</code> library:</p>
<pre><code class="lang-auto">ModuleNotFoundError: No module named 'requests'
</code></pre>
<p>So I then did</p>
<pre><code class="lang-auto">conda install requests
pyspice-post-installation --install-ngspice-dll
pyspice-post-installation --check-install
</code></pre>
<p>And it worked.  I reported the dependency problem here: <a href="https://github.com/FabriceSalvaire/PySpice/issues/266" rel="noopener nofollow ugc">https://github.com/FabriceSalvaire/PySpice/issues/266</a></p>
<h2>Windows 7</h2>
<p>Now I’m doing the same procedure on a Windows 7 machine (I know, I know, it’s obsolete).  The install command showed no errors on the command line, but I did get a pop up error:</p>
<blockquote>
<p>python.exe - System Error</p>
<p>The program can’t start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.</p>
<p>OK</p>
</blockquote>
<p>I haven’t seen this error before, but the install command worked so I’m ignoring it.</p>
<p>Then I try</p>
<pre><code class="lang-auto">pyspice-post-installation --install-ngspice-dll
</code></pre>
<p>Ah, now I’m getting the same error:</p>
<blockquote>
<p>python.exe - System Error</p>
<p>The program can’t start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.</p>
<p>OK</p>
</blockquote>
<p>and if I run the check:</p>
<pre><code class="lang-auto">pyspice-post-installation --check-install
</code></pre>
<p>I get the same error dialog:</p>
<blockquote>
<p>python.exe - System Error</p>
<p>The program can’t start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.</p>
<p>OK</p>
</blockquote>
<p>Tried System File Checker:</p>
<pre><code class="lang-auto">λ sfc /scannow

Beginning system scan.  This process will take some time.

Beginning verification phase of system scan.
Verification 100% complete.

Windows Resource Protection did not find any integrity violations.
</code></pre>
<p>Searching my machine, it does not have <code>api-ms-win-core-path-l1-1-0.dll</code> anywhere.  Maybe this is a Windows 10 file only.  (Nope, not present on Windows 10 machine, either.)</p>
<p>Trying to install jupyterlab also doesn’t work well.  Does PySpice have some weird requirements/dependencies that prevent conda from installing it alongside other things?</p>
<pre><code class="lang-auto">Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
</code></pre>
<p>Oh if I do it as <code>conda install jupyterlab voila</code> instead of using conda-forge, it works fine</p>
            <p><small>2 posts - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/two-installation-experiences-on-windows/107">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/two-installation-experiences-on-windows/107</link>
          <pubDate>Wed, 16 Dec 2020 15:28:34 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-107</guid>
          <source url="https://pyspice.discourse.group/t/two-installation-experiences-on-windows/107.rss">Two installation experiences on Windows</source>
        </item>
        <item>
          <title>Simulating Dependent Sources (CCVS works but VCVS does not?!)</title>
          <dc:creator><![CDATA[dsalman]]></dc:creator>
          <category>Circuit Simulation</category>
          <description><![CDATA[
            <p>Hello,</p>
<p>I am trying to run the following code for the circuit:<img src="https://aws1.discourse-cdn.com/free1/uploads/pyspice/original/1X/f64e6081e7b1e978c67c509c0bc720c59812d89b.jpeg" alt="Circuit" data-base62-sha1="z8VnxkVFbzhUCrIYUKthum2afhN" width="530" height="232"></p>
<p>###############################################################</p>
<p>import PySpice.Logging.Logging as Logging<br>
logger = Logging.setup_logging()</p>
<p>################################################################</p>
<p>from PySpice.Spice.Netlist import Circuit<br>
from PySpice.Unit import *</p>
<p>#################################################################</p>
<p>circuit = Circuit(‘Circuit with VCVS’)</p>
<p>circuit.R(1, 1, circuit.gnd, 6@u_Ω)<br>
circuit.R(2, 2, 3,           4@u_Ω)<br>
circuit.R(3, 3, 4,           8@u_Ω)<br>
circuit.R(4, 5, circuit.gnd, 15@u_Ω)<br>
circuit.V(1, 2, 1,           65@u_V)<br>
circuit.E(1, 4, 3, 2, 3, 3)</p>
<p>simulator = circuit.simulator(temperature=25, nominal_temperature=25)<br>
analysis = simulator.operating_point()</p>
<p>for node in analysis.nodes.values():<br>
print(‘Node {}: {:4.1f} V’.format(str(node), float(node)))</p>
<p>When I run, it gives an error:</p>
<p>Traceback (most recent call last):<br>
File “C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\PySpice\Spice\Netlist.py”, line 928, in <strong>getattr</strong><br>
return self.<strong>getitem</strong>(attribute_name)<br>
File “C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\PySpice\Spice\Netlist.py”, line 921, in <strong>getitem</strong><br>
raise IndexError(attribute_name) # KeyError<br>
IndexError: E</p>
<p>During handling of the above exception, another exception occurred:</p>
<p>Traceback (most recent call last):<br>
File “C:/Users/Desktop/PySpice/node-voltage-method-example8.py”, line 22, in <br>
circuit.E(1, 4, 3, 2, 3, 3)<br>
File “C:\Users\AppData\Local\Programs\Python\Python39\lib\site-packages\PySpice\Spice\Netlist.py”, line 930, in <strong>getattr</strong><br>
raise AttributeError(attribute_name)<br>
AttributeError: E</p>
<p>I am not sure where I am going wrong. I have been able to simulate a CCVS (part name H) but all other dependent sources seem to give an error.</p>
<p>Can anyone please point out what is wrong in the code above?</p>
<p>Thanks</p>
<p>Salman</p>
            <p><small>6 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/simulating-dependent-sources-ccvs-works-but-vcvs-does-not/105">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/simulating-dependent-sources-ccvs-works-but-vcvs-does-not/105</link>
          <pubDate>Wed, 02 Dec 2020 01:58:43 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-105</guid>
          <source url="https://pyspice.discourse.group/t/simulating-dependent-sources-ccvs-works-but-vcvs-does-not/105.rss">Simulating Dependent Sources (CCVS works but VCVS does not?!)</source>
        </item>
        <item>
          <title>Bode plot with sinusoidal Current Source</title>
          <dc:creator><![CDATA[IanJannasch]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>Hi,</p>
<p>I successfully ran this example: <a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/examples/filter/low-pass-rc-filter.html" rel="noopener nofollow ugc">https://pyspice.fabrice-salvaire.fr/releases/v1.4/examples/filter/low-pass-rc-filter.html</a></p>
<p>I am however interested in replacing the voltage source with a current source and still get a bode plot that compares the output voltage to input current. Just replacing the voltage source with a current source as follows gives me an error.</p>
<p>circuit.SinusoidalCurrentSource(‘input’, ‘in’, circuit.gnd, amplitude=1@u_uA)</p>
<p><strong>NgSpiceCommandError</strong> : Command ‘run’ failed</p>
<p>Thank you in advance</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/bode-plot-with-sinusoidal-current-source/103">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/bode-plot-with-sinusoidal-current-source/103</link>
          <pubDate>Tue, 24 Nov 2020 12:13:04 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-103</guid>
          <source url="https://pyspice.discourse.group/t/bode-plot-with-sinusoidal-current-source/103.rss">Bode plot with sinusoidal Current Source</source>
        </item>
        <item>
          <title>Is PySpice 1.4.2 compatible with Ngspice 33?</title>
          <dc:creator><![CDATA[Bha]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>Hello Community,</p>
<p>I have set up PySpice 1.4.2 through a virtual environment and brew installed Ngspice and libngspice on Mac 0S X. However, “pyspice-post-installation --check-install” tells me that Ngspice version 33 is not supported.</p>
<p>Please advise.</p>
            <p><small>2 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/is-pyspice-1-4-2-compatible-with-ngspice-33/101">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/is-pyspice-1-4-2-compatible-with-ngspice-33/101</link>
          <pubDate>Mon, 23 Nov 2020 02:57:05 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-101</guid>
          <source url="https://pyspice.discourse.group/t/is-pyspice-1-4-2-compatible-with-ngspice-33/101.rss">Is PySpice 1.4.2 compatible with Ngspice 33?</source>
        </item>
        <item>
          <title>Using the Skywater PDK with SKiDL/PySpice</title>
          <dc:creator><![CDATA[devbisme]]></dc:creator>
          <category>Uncategorized</category>
          <description><![CDATA[
            <p>I’ve published a <a href="https://github.com/xesscorp/skidl/blob/development/examples/skywater/skywater.ipynb" rel="noopener nofollow ugc">Jupyter notebook</a> of my explorations using SKiDL and PySpice with the open Skywater PDK.</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/using-the-skywater-pdk-with-skidl-pyspice/98">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/using-the-skywater-pdk-with-skidl-pyspice/98</link>
          <pubDate>Mon, 16 Nov 2020 18:41:20 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-98</guid>
          <source url="https://pyspice.discourse.group/t/using-the-skywater-pdk-with-skidl-pyspice/98.rss">Using the Skywater PDK with SKiDL/PySpice</source>
        </item>
        <item>
          <title>Losing units when summing a Waveform</title>
          <dc:creator><![CDATA[devbisme]]></dc:creator>
          <category>Data Analysis using Python</category>
          <description><![CDATA[
            <p>I multiplied two Waveform objects: one containing voltages and the other containing currents. Then I multiplied it by a PeriodValue. As expected, the resulting Wavform object contains numbers with the units of Joules. But when I applied the sum() method to this Waveform, I got a scalar value with no units.</p>
<p>Is there any way to do this without losing the units for the calculations that follow?</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/losing-units-when-summing-a-waveform/97">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/losing-units-when-summing-a-waveform/97</link>
          <pubDate>Fri, 06 Nov 2020 15:07:46 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-97</guid>
          <source url="https://pyspice.discourse.group/t/losing-units-when-summing-a-waveform/97.rss">Losing units when summing a Waveform</source>
        </item>
        <item>
          <title>Load_circuit failing for some reasons</title>
          <dc:creator><![CDATA[asav86]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <hr>
<ul>
<li>OS: MacOS Catilina (version 10.15.7)</li>
<li>Python framework with PyCharm + Conda environment</li>
<li>PySpice installed with Conda (version 1.4.3)</li>
<li>libngspice installed with Conda</li>
<li>NGSPICE installed with homebrew (version 33)
<ul>
<li>location: /usr/local/bin/ngspice</li>
<li>functionality check: NGSPICE works from terminal and does simulate a circuit</li>
</ul>
</li>
</ul>
<hr>
<p>Hi,</p>
<p>this is my first test with the “PySpice” flow. I went through the explained installation steps:</p>
<aside class="onebox allowlistedgeneric">
  <header class="source">
      <a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/installation.html" target="_blank" rel="noopener nofollow ugc">pyspice.fabrice-salvaire.fr</a>
  </header>
  <article class="onebox-body">
    <img src="" class="thumbnail" width="" height="">

<h3><a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/installation.html" target="_blank" rel="noopener nofollow ugc">4. Installation — PySpice 1.4.2 documentation</a></h3>



  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

<p>By running the “resistor-bridge.py” example:</p>
<aside class="onebox allowlistedgeneric">
  <header class="source">
      <a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/examples/resistor/resistor-bridge.html" target="_blank" rel="noopener nofollow ugc">pyspice.fabrice-salvaire.fr</a>
  </header>
  <article class="onebox-body">
    <img src="" class="thumbnail" width="" height="">

<h3><a href="https://pyspice.fabrice-salvaire.fr/releases/v1.4/examples/resistor/resistor-bridge.html" target="_blank" rel="noopener nofollow ugc">8.15.1. Resistor Bridge — PySpice 1.4.2 documentation</a></h3>



  </article>
  <div class="onebox-metadata">
    
    
  </div>
  <div style="clear: both"></div>
</aside>

<p>I get the following error:</p>
<p>…<br>
PySpice.Spice.NgSpice.Shared.NgSpiceCommandError: Command ‘run’ failed<br>
…</p>
<p>By placing a breakpoint and debugging the code I see that the failing point is at (every line nested hierarchically):</p>
<p>analysis = simulator.operating_point()<br>
return self._run(‘operating_point’, *args, **kwargs)<br>
self._ngspice_shared.run()<br>
self.exec_command(command)<br>
raise NgSpiceCommandError(“Command ‘{}’ failed”.format(command))</p>
<p>And is due to stderr = ‘Error: there aren’t any circuits loaded.’</p>
<p>By debugging further I could nail down that the def run() method of the Simulation class fails because the run command after the load_circuit command complains that the circuit wasn’t loaded.</p>
<pre><code>def _run(self, analysis_method, *args, **kwargs):

    super()._run(analysis_method, *args, **kwargs)

    self._ngspice_shared.destroy()
    # Fixme: Error: circuit not parsed.
    self._ngspice_shared.load_circuit(str(self))
    self._ngspice_shared.run()
    self._logger.debug(str(self._ngspice_shared.plot_names))
    self.reset_analysis()

    plot_name = self._ngspice_shared.last_plot
    if plot_name == 'const':
        raise NameError('Simulation failed')

    return self._ngspice_shared.plot(self, plot_name).to_analysis()
</code></pre>
<p>So the load_circuit method seems to not load the circuit properly in the sim, any idea why? (although it does execute it and no error is raised within that method).</p>
<p>I tried also the listing() method to query the circuit description back and also doesn’t seem to provide anything back.</p>
<p>Actually the only communication with the simulator seems to be successful is the “version -f” command which returns the valuable infos from it.</p>
<p>Thanks,<br>
Andrea</p>
            <p><small>3 posts - 2 participants</small></p>
            <p><a href="https://pyspice.discourse.group/t/load-circuit-failing-for-some-reasons/96">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/load-circuit-failing-for-some-reasons/96</link>
          <pubDate>Mon, 02 Nov 2020 20:14:10 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-96</guid>
          <source url="https://pyspice.discourse.group/t/load-circuit-failing-for-some-reasons/96.rss">Load_circuit failing for some reasons</source>
        </item>
        <item>
          <title>Trouble with Libraries</title>
          <dc:creator><![CDATA[JOALCO]]></dc:creator>
          <category>Help</category>
          <description><![CDATA[
            <p>Hello!</p>
<p>To better understand PySpice, I’m working through a very simple circuit involving a voltage source, a resistor, and a 1N4148 Diode.  However, I am having trouble with Python recognizing the library I need to bring in the characteristics of the diode. Here is my code:</p>
<p>'import numpy as np<br>
import matplotlib.pyplot as plt<br>
import matplotlib.ticker as ticker</p>
<p>import PySpice.Logging.Logging as Logging<br>
logger = Logging.setup_logging()</p>
<p>from PySpice.Doc.ExampleTools import find_libraries<br>
from PySpice.Spice.Netlist import Circuit<br>
from PySpice.Spice.Library import SpiceLibrary<br>
from PySpice.Unit import *<br>
from PySpice.Physics.SemiConductor import ShockleyDiode</p>
<p>libraries_path = find_libraries()<br>
spice_library = SpiceLibrary(libraries_path)</p>
<p>circuit = Circuit(‘Diode Characteristic Curve’)</p>
<p>circuit.include(spice_library[‘1N4148’])</p>
<p>circuit.V(‘input’, ‘in’, circuit.gnd, 10@u_V)<br>
circuit.R(1, ‘in’, ‘out’, 1@u_Ω) # not required for simulation<br>
circuit.X(‘D1’, ‘1N4148’, ‘out’, circuit.gnd)’</p>
<p>And here is my result:</p>
<p>’ <code>---------------------------------------------------------------------------</code> <code>KeyError                                  Traceback (most recent call last)</code> <code>&lt;ipython-input-5-ae802129d891&gt; in &lt;module&gt;      20 circuit = Circuit('Diode Characteristic Curve')      21  ---&gt; 22 circuit.include(spice_library['1N4148'])      23       24 circuit.V('input', 'in', circuit.gnd, 10@u_V)</code> <code>/usr/local/lib/python3.8/dist-packages/PySpice/Spice/Library.py in __getitem__(self, name)     105             # print('Library {} not found in {}'.format(name, self._directory))     106             # self._logger.warn('Library {} not found in {}'.format(name, self._directory)) --&gt; 107             raise KeyError(name)     108      109     ##############################################</code> <code>KeyError: '1N4148'</code>’</p>
<p>Can anyone help me understand what exactly is going wrong here and how I can correct it?</p>
<p>Thanks!</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/trouble-with-libraries/94">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/trouble-with-libraries/94</link>
          <pubDate>Sun, 25 Oct 2020 20:45:42 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-94</guid>
          <source url="https://pyspice.discourse.group/t/trouble-with-libraries/94.rss">Trouble with Libraries</source>
        </item>
        <item>
          <title>Install Pyspice on Raspberry Pi 4 ERROR</title>
          <dc:creator><![CDATA[LencsesDaniel]]></dc:creator>
          <category>Installation</category>
          <description><![CDATA[
            <p>Hello Everyone!<br>
I’m running into a problem, i want to install PySpice on Raspberry Pi 4 which runs Raspbian OS. I have read the doumentation that wrote, it is supported on Linux, Windos 64 and MAC.<br>
I have followed the install instructions after i typed : pip3 install PySpice the following error message i got:</p>
<p>Defaulting to user installation because normal site-packages is not writeable<br>
Looking in indexes: <a href="https://pypi.org/simple" rel="noopener nofollow ugc">https://pypi.org/simple</a>, <a href="https://www.piwheels.org/simple" rel="noopener nofollow ugc">https://www.piwheels.org/simple</a><br>
Collecting PySpice<br>
Using cached PySpice-1.4.3-py2.py3-none-any.whl (144 kB)<br>
Collecting scipy&gt;=1.4<br>
Downloading scipy-1.5.3.tar.gz (25.2 MB)<br>
|################################| 25.2 MB 28 kB/s<br>
Installing build dependencies … \Ledone<br>
Getting requirements to build wheel … done<br>
Preparing wheel metadata … error<br>
ERROR: Command errored out with exit status 1:<br>
command: /usr/bin/python /home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpv39ep59r<br>
cwd: /tmp/pip-install-_1dtpvzc/scipy<br>
Complete output (139 lines):<br>
lapack_opt_info:<br>
lapack_mkl_info:<br>
customize UnixCCompiler<br>
libraries mkl_rt not found in [’/usr/local/lib’, ‘/usr/lib’, ‘/usr/lib/arm-linux-gnueabihf’]<br>
NOT AVAILABLE</p>
<pre><code>openblas_lapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
  NOT AVAILABLE

openblas_clapack_info:
customize UnixCCompiler
customize UnixCCompiler
  libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
  NOT AVAILABLE

flame_info:
customize UnixCCompiler
  libraries flame not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
  NOT AVAILABLE

atlas_3_10_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
customize UnixCCompiler
  libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
&lt;class 'numpy.distutils.system_info.atlas_3_10_threads_info'&gt;
  NOT AVAILABLE

atlas_3_10_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
customize UnixCCompiler
  libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
&lt;class 'numpy.distutils.system_info.atlas_3_10_info'&gt;
  NOT AVAILABLE

atlas_threads_info:
Setting PTATLAS=ATLAS
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
customize UnixCCompiler
  libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
&lt;class 'numpy.distutils.system_info.atlas_threads_info'&gt;
  NOT AVAILABLE

atlas_info:
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/local/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib
customize UnixCCompiler
  libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
customize UnixCCompiler
  libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
&lt;class 'numpy.distutils.system_info.atlas_info'&gt;
  NOT AVAILABLE

accelerate_info:
  NOT AVAILABLE

lapack_info:
customize UnixCCompiler
  libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
  NOT AVAILABLE

lapack_src_info:
  NOT AVAILABLE

  NOT AVAILABLE

setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-yx7fyy34'), proceeding with generating Cython sources and expanding templates
  warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
Running from SciPy source directory.
/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  if getattr(self, '_calc_info_{}'.format(lapack))():
/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  if getattr(self, '_calc_info_{}'.format(lapack))():
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in &lt;module&gt;
    main()
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
    return hook(metadata_directory, config_settings)
  File "/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
    self.run_setup()
  File "/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 583, in &lt;module&gt;
    setup_package()
  File "setup.py", line 579, in setup_package
    setup(**metadata)
  File "/tmp/pip-build-env-pdkw0rfi/overlay/lib/python3.8/site-packages/numpy/distutils/core.py", line 137, in setup
    config = configuration()
  File "setup.py", line 477, in configuration
    raise NotFoundError(msg)
numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
----------------------------------------
</code></pre>
<p>ERROR: Command errored out with exit status 1: /usr/bin/python /home/pi/.local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpv39ep59r Check the logs for full command output.</p>
<p>Is it because i have <a href="https://en.wikipedia.org/wiki/ARM_Cortex-A72" rel="noopener nofollow ugc">ARM Cortex-A72</a> architecture and not x64? Or is it because Raspbian and not exactly Linux? But raspbian based on Linux…</p>
<p>Thanks for all answers!<br>
Best regards,<br>
Daniel</p>
            <p><small>1 post - 1 participant</small></p>
            <p><a href="https://pyspice.discourse.group/t/install-pyspice-on-raspberry-pi-4-error/90">Read full topic</a></p>
          ]]></description>
          <link>https://pyspice.discourse.group/t/install-pyspice-on-raspberry-pi-4-error/90</link>
          <pubDate>Mon, 19 Oct 2020 17:38:42 +0000</pubDate>
          <discourse:topicPinned>No</discourse:topicPinned>
          <discourse:topicClosed>No</discourse:topicClosed>
          <discourse:topicArchived>No</discourse:topicArchived>
          <guid isPermaLink="false">pyspice.discourse.group-topic-90</guid>
          <source url="https://pyspice.discourse.group/t/install-pyspice-on-raspberry-pi-4-error/90.rss">Install Pyspice on Raspberry Pi 4 ERROR</source>
        </item>
  </channel>
</rss>
